### ISSUE TITLE
data

### ISSUE THREAD

**Issue by wangzeyu135798** [rootlu/L2P-GNN#1]
Hi:
    I use dblp dataset you published. When I run your code, there  is a wrong "No such file or directory ../data/dblp/graph ", while there is no graph file or directory under unziped dblp directory.

**Comment by rootlu** [comment]
Hi,

You need to first download the dblp dataset from [Google Drive](https://drive.google.com/drive/folders/18vpBvSajIrme2xsbx8Oq8aTWIWMlSgJT?usp=sharing) or [BaiduYun](https://pan.baidu.com/s/1Yv6dN7F1jgTSz9-nU1eN-A), and unzip the dataset.

Then, make two directories named `unsupervised` and `supervised` in `./data/dblp/` (i.e., `./data/dblp/unsupervised` and `./data/dblp/supervised/` ), and move the `dblp.graph` file to `./data/dblp/unsupervised/processed/` and the `dblpfinetune.graph` to `./data/dblp/supervised/processed/`, respectively.

We have updated the README file to detail the requirements.

Thanks for your interest in our work!

**Comment by wangzeyu135798** [comment]
Hi:
    I changed the data path according to your reply while there is another problem when processing data.
    In loader.py line 323,  when I load the dblp.graph, where is a problem as following:
    UnicodeDecodeError:  'unit-8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by rootlu** [comment]
Hi,

Due to the dblp dataset is large, this error may occur when the file download is incomplete，please make sure that you have downloaded the dataset without any errors (e.g., Internet interruption).

Meanwhile, we are double-checking whether the uploaded dataset is complete, and we will update the README as soon as possible.

If you want to reproduce results in the paper, you can refer to `Reproducing results in the paper` in the READEME. Also, you can run the code with the Biology dataset first.

Thanks.

**Comment by rootlu** [comment]
Hi,

We have double-checked that the uploaded dataset is complete. You can try to download and run it again. 
We have also uploaded the uncompressed dataset, please refer to [BaiduYun](https://pan.baidu.com/s/1Yv6dN7F1jgTSz9-nU1eN-A) to download.

Bests.
